export const metrics = [
  {
    title: "Total Orders",
    value: "123",
    change: "28%",
    isPositive: true,
    icon: "/shopping-bag.svg",
    subtitle: "From The Last Month",
  },
  {
    title: "Total Taken",
    value: "123",
    change: "15%",
    isPositive: false,
    icon: "/shopping-bag.svg",
    subtitle: "From The Last Month",
  },
  {
    title: "Total Revenue",
    value: "123",
    change: "28%",
    isPositive: true,
    icon: "/shopping-bag.svg",
    subtitle: "From The Last Month",
  },
  {
    title: "Pending Orders",
    value: "$1234.99",
    change: "28%",
    isPositive: true,
    icon: "/shopping-bag.svg",
    subtitle: "From The Last Month",
  },
  {
    title: "Pending Returns",
    value: "$1234.99",
    change: "28%",
    isPositive: true,
    icon: "/shopping-bag.svg",
    subtitle: "From The Last Month",
  },
];

export const orders = [
  {
    product: "Product First",
    channel: "ebay",
    customer: "Beatrice Gilbert",
    date: "Today",
    total: "123",
  },
  {
    product: "Product First",
    channel: "ebay",
    total: "123",
    customer: "Mike Simmons",
    date: "Today",
  },
  {
    product: "Fresh Bun Product",
    channel: "ebay",
    total: "123",
    customer: "Jim Pierce",
    date: "Tomorrow",
  },
  {
    product: "Biscuit - Beef Burger",
    channel: "facebook",
    total: "123",
    customer: "Brandi Gilbert",
    date: "Tomorrow",
  },
  {
    product: "Puffed Corn Snacks",
    channel: "ebay",
    total: "123",
    customer: "Nancy Rice",
    date: "01/01/2025",
  },
];

export const activities = [
  {
    id: 1,
    user: "Christian Wood",
    action: "Sent Message to",
    target: "Nikita Houston",
    time: "1 min ago",
    type: "message",
    avatar: "CW",
    date: "TODAY",
  },
  {
    id: 2,
    user: "Nikita Houston",
    action: "Reply your message",
    target: '"Hello"',
    time: "1 min ago",
    type: "reply",
    avatar: "NH",
    date: "TODAY",
  },
  {
    id: 3,
    user: "Christian Wood",
    action: "Accept Order from",
    target: "Ebay",
    time: "1 min ago",
    type: "order",
    avatar: "CW",
    date: "TODAY",
  },
  {
    id: 4,
    user: "Rohan Walker",
    action: "Reply your message",
    target: "Ebay",
    time: "1 min ago",
    type: "reply",
    avatar: "RW",
    date: "TODAY",
  },
  {
    id: 5,
    user: "Rohan Walker",
    action: "Reply your message",
    target: "Ebay",
    time: "1 min ago",
    type: "reply",
    avatar: "RW",
    date: "TODAY",
  },
  {
    id: 6,
    user: "Christian Wood",
    action: "Accept Order from",
    target: "Amazon",
    time: "12:30PM",
    type: "order",
    avatar: "CW",
    date: "YESTERDAY",
  },
  {
    id: 7,
    user: "Christian Wood",
    action: "Accept Order from",
    target: "Walmart",
    time: "11:20AM",
    type: "order",
    avatar: "CW",
    date: "25 MAY 2024",
  },
  {
    id: 8,
    user: "Christian Wood",
    action: "Accept Order from",
    target: "Walmart",
    time: "11:20AM",
    type: "order",
    avatar: "CW",
    date: "25 MAY 2024",
  },
];
